import { createSlice } from "@reduxjs/toolkit";

// Initial state should be an object representing the authentication state.
const initialState = {
  isAuthenticated: false,
};

const authSlice = createSlice({
  name: "auth",
  initialState,
  reducers: {
    login: (state) => {
      // Update the state to indicate that the user is authenticated.
      state.isAuthenticated = true;
    },
    logout: (state) => {
      // Update the state to indicate that the user is not authenticated.
      state.isAuthenticated = false;
    },
  },
});

// Export the action creators generated by createSlice.
export const { login, logout } = authSlice.actions;

// Export the reducer.
export default authSlice.reducer;
